# everything is from the original config, except for the batch size

device: &device 'cuda'

model:
  autoencoder:
    optimizer_class: "${as_class: 'torch.optim.AdamW'}"
    optimizer_kwargs:
      lr: 0.001
      betas: [0.5, 0.9]
      weight_decay: 0.001
    lr_scheduler: 
      class: "${as_class: 'torch.optim.lr_scheduler.ReduceLROnPlateau'}"
      kwargs:
        patience: 3
        factor: 0.25
        verbose: True
      extra:
        monitor: 'val/rec_loss'
        frequency: 1
        interval: 'epoch'
    antialiaser:
      use: True
      kwargs:
          device: *device
    encoder: {}
    decoder: {}
    net_kwargs:
      hidden_width: &autoencoder_hidden_width 32
    loss:
      kl_weight: 0.01
    device: *device
        
  ldm:
    device: *device
    conditioner:
      autoencoder_dim: *autoencoder_hidden_width
      output_patches: &output_patches 5
      cascade_depth: 3
      embed_dim: 128
      analysis_depth: 4
    denoiser:
      in_channels: *autoencoder_hidden_width
      model_channels: 256
      out_channels: *autoencoder_hidden_width
      num_res_blocks: 2
      attention_resolutions: [1, 2]
      dims: 3
      channel_mult: [1, 2, 4]
      num_heads: 8
      num_timesteps: *output_patches
      context_ch: [128, 256, 512] # should be equal to conditioner.cascade_dims ?
    ema:
      use: True
      kwargs:
        store_device: 'cpu'
    optimizer_class: "${as_class: 'torch.optim.AdamW'}"
    optimizer_kwargs:
      lr: 0.0001
      betas: [0.5, 0.9]
      weight_decay: 0.001
    lr_scheduler: 
      class: "${as_class: 'torch.optim.lr_scheduler.ReduceLROnPlateau'}"
      kwargs:
        patience: 3
        factor: 0.25
        verbose: True
      extra:
        monitor: 'val/ema_loss'
        frequency: 1
        interval: 'epoch'
    scheduler: {} # diffusion scheduler

dataloader:
  batch_size: 32
  num_workers: 4
  persistent_workers: True

trainer:
  max_epochs: 200
  accelerator: 'gpu'
  log_every_n_steps: 5
  callbacks: "${as_class: '[pl.callbacks.EarlyStopping(\"val/rec_loss\", patience=6, verbose=True, check_finite=False)]'}"

sampled_radar_dataset:
  zarr_path: 'test.zarr'
  csv_path: 'mlcast-dataset-sampler/sampled_datacubes_2017-01-01-2017-02-01_24x256x256_3x16x16_10000.csv'
  steps: 24
  augment: False
  data_var: 'precip_intensity_EDK'


