autoencoder_hidden_width: &autoencoder_hidden_width 32

conditioner:
    autoencoder_dim: *autoencoder_hidden_width
    output_patches: &output_patches 5
    cascade_depth: 3
    embed_dim: 128
    analysis_depth: 4

denoiser:
    in_channels: *autoencoder_hidden_width
    model_channels: 256
    out_channels: *autoencoder_hidden_width
    num_res_blocks: 2
    attention_resolutions: [1, 2]
    dims: 3
    channel_mult: [1, 2, 4]
    num_heads: 8
    num_timesteps: *output_patches
    context_ch: [128, 256, 512] # should be equal to conditioner.cascade_dims ?

ema:
    use: True
    kwargs:
        store_device: 'cpu'
    